language: node_js
node_js: "node"
cache: "npm"
env:
  global:
    - POSTGRES_DB=device
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=
    - PUBLIC_KEY=test-public-key
    - DATABASE_URL=postgresql://postgres@localhost:5432/device
services:
  - postgresql
before_install:
  - psql -c "CREATE DATABASE device;" -U postgres
install:
  - npm install npm@latest -g
  - npm install
script:
  - npm run test:coverage
notifications:
  email:
    on_success: never
    on_failure: always
